In [414]:
import os
import glob
import pandas as pd

In [415]:
files = glob.glob(os.getcwd() + "\\data\\*.csv")

In [416]:
all_dfs = []

for file in files:
    try:
        temp_df = pd.read_csv(file, encoding='utf-8')
        all_dfs.append(temp_df)
    except Exception as e:
        print(f"❌ Could not read {file} due to: {e}")

❌ Could not read C:\Users\kolia\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\Scripts\football_test\data\03-04.csv due to: Error tokenizing data. C error: Expected 57 fields in line 305, saw 72

❌ Could not read C:\Users\kolia\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\Scripts\football_test\data\04-05.csv due to: Error tokenizing data. C error: Expected 57 fields in line 337, saw 62

In [417]:
# Concatenate all successfully read files
if all_dfs:
    df = pd.concat(all_dfs, ignore_index=True)
    print(f"✅ Success! Combined DataFrame shape: {df.shape}")
else:
    print("❌ No files were successfully read.")

✅ Success! Combined DataFrame shape: (8031, 206)

In [419]:
df = df[df.columns[:list(df.columns).index("B365H")]]

df.columns

Index(['Div', 'Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG',
       'HTAG', 'HTR', 'Referee', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC',
       'AC', 'HY', 'AY', 'HR', 'AR'],
      dtype='object')

In [420]:
df.head()

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
0,E0,13/08/05,Aston Villa,Bolton,2.0,2.0,D,2.0,2.0,D,...,2.0,6.0,14.0,16.0,7.0,8.0,0.0,2.0,0.0,0.0
1,E0,13/08/05,Everton,Man United,0.0,2.0,A,0.0,1.0,A,...,5.0,5.0,15.0,14.0,8.0,6.0,3.0,1.0,0.0,0.0
2,E0,13/08/05,Fulham,Birmingham,0.0,0.0,D,0.0,0.0,D,...,7.0,4.0,12.0,13.0,6.0,6.0,1.0,2.0,0.0,0.0
3,E0,13/08/05,Man City,West Brom,0.0,0.0,D,0.0,0.0,D,...,8.0,3.0,13.0,11.0,3.0,6.0,2.0,3.0,0.0,0.0
4,E0,13/08/05,Middlesbrough,Liverpool,0.0,0.0,D,0.0,0.0,D,...,2.0,7.0,17.0,11.0,5.0,0.0,2.0,3.0,1.0,0.0

In [421]:
df['Date'] = pd.to_datetime(df['Date'], format='mixed')
df['Date'].min()

Timestamp('2005-01-10 00:00:00')

In [422]:
df.head()

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
0,E0,2005-08-13,Aston Villa,Bolton,2.0,2.0,D,2.0,2.0,D,...,2.0,6.0,14.0,16.0,7.0,8.0,0.0,2.0,0.0,0.0
1,E0,2005-08-13,Everton,Man United,0.0,2.0,A,0.0,1.0,A,...,5.0,5.0,15.0,14.0,8.0,6.0,3.0,1.0,0.0,0.0
2,E0,2005-08-13,Fulham,Birmingham,0.0,0.0,D,0.0,0.0,D,...,7.0,4.0,12.0,13.0,6.0,6.0,1.0,2.0,0.0,0.0
3,E0,2005-08-13,Man City,West Brom,0.0,0.0,D,0.0,0.0,D,...,8.0,3.0,13.0,11.0,3.0,6.0,2.0,3.0,0.0,0.0
4,E0,2005-08-13,Middlesbrough,Liverpool,0.0,0.0,D,0.0,0.0,D,...,2.0,7.0,17.0,11.0,5.0,0.0,2.0,3.0,1.0,0.0

In [423]:
df[df['Div'].isna()]

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
3800,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [424]:
df = df[df['Div'].notna()]
df = df.sort_values(by="Date", ascending=True)

In [425]:
X = df.loc[:, df.columns != 'FTR']
Y = df['FTR']

In [426]:
X.to_hdf("data.h5", key="Features", mode="w")
Y.to_hdf("data.h5", key="Labels", mode="a")